#!/usr/bin/env bash
# Idempotent repository bootstrap for Cloud Agent development.
# - Installs Node dependencies from the lockfile.
# - Ensures PostgreSQL is installed and a local cluster + schema exist.
# - Writes .env.local with the local dev DATABASE_URL and INGEST_SECRET.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_DIR"

echo "==> Installing Node dependencies (npm ci)"
npm ci

# Ensure PostgreSQL server binaries are present (idempotent).
if ! ls /usr/lib/postgresql/*/bin/pg_ctl >/dev/null 2>&1; then
  echo "==> Installing PostgreSQL"
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-contrib
fi

# shellcheck source=/dev/null
source "$SCRIPT_DIR/pg-env.sh"

# Initialize the local cluster, start the server, and apply the schema so the
# working state is captured in the environment snapshot.
"$SCRIPT_DIR/start.sh"

# Write local development environment variables consumed by Next.js.
# .env* is gitignored, so this stays local to the environment.
ENV_FILE="$REPO_DIR/.env.local"
if [ ! -f "$ENV_FILE" ] || ! grep -q '^DATABASE_URL=' "$ENV_FILE"; then
  echo "==> Writing $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Local development configuration (generated by .cursor/install.sh).
DATABASE_URL=$DEV_DATABASE_URL
INGEST_SECRET=dev-ingest-secret
EOF
fi

echo "==> Install complete"
